# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "dict"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"